apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmgard
  namespace: default
  labels:
    app: irmgard
spec:
  selector:
    matchLabels:
      app: irmgard
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: irmgard
    spec:
      containers:
      - name: irmgard
        image: fischerjulian/irmgard:0.3.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_USERNAME
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_HOST
        ports:
        - containerPort:  8080
          name: irmgard
      restartPolicy: Always